# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 295)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_generate = QtWidgets.QPushButton(self.centralwidget)
        self.bt_generate.setGeometry(QtCore.QRect(50, 240, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bt_generate.setFont(font)
        self.bt_generate.setStyleSheet("background: (85, 0, 127);\n"
"color: (0, 255, 0);\n"
"border: 2.5px solid #33168a;\n"
"border-radius: #168a20")
        self.bt_generate.setObjectName("bt_generate")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(50, 10, 231, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setStyleSheet("background: (170, 85, 0);\n"
"color: (85, 0, 127)")
        self.title.setObjectName("title")
        self.cb_numbers = QtWidgets.QRadioButton(self.centralwidget)
        self.cb_numbers.setGeometry(QtCore.QRect(30, 150, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        self.cb_numbers.setFont(font)
        self.cb_numbers.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cb_numbers.setObjectName("cb_numbers")
        self.cb_alphabet = QtWidgets.QRadioButton(self.centralwidget)
        self.cb_alphabet.setGeometry(QtCore.QRect(30, 190, 168, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_alphabet.setFont(font)
        self.cb_alphabet.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cb_alphabet.setObjectName("cb_alphabet")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(30, 90, 123, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result.setFont(font)
        self.result.setStyleSheet("")
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_generate.setText(_translate("MainWindow", "Згенерувати"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.cb_numbers.setText(_translate("MainWindow", "використовувати числа"))
        self.cb_alphabet.setText(_translate("MainWindow", "викоритовувати алфавіт"))
        self.result.setText(_translate("MainWindow", "Результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
